
responses = [
  "I think so Brainini but arugula flavoured gelato?",
  "I think so, Brain, but where are we going to find a duck and a hose at this hour?",
  "I think so, but where will we find an open tattoo parlor at this time of night?",
  "Wuh, I think so, Brain, but if we didn't have ears, we'd look like weasels.",
  "Uh... yeah, Brain, but where are we going to find rubber pants our size?",
  "Uh, I think so, Brain, but balancing a family and a career ... ooh, it's all too much for me.",
  "Wuh, I think so, Brain, but isn't <https://en.wikipedia.org/wiki/Regis Philbin|Regis Philbin> already married?",
  "Wuh, I think so, Brain, but <https://en.wikipedia.org/wiki/Burlap|burlap> chafes me so.",
  "Sure, Brain, but how are we going to find <https://en.wikipedia.org/wiki/Chaps|chaps> our size?",
  "Uh, I think so, Brain, but we'll never get a monkey to use dental floss.",
  "Are you pondering cheesesticks?",
  "Uh, I think so Brain, but this time, you wear the tutu.",
  "I think so, Brain, but <https://en.wikipedia.org/wiki/Culottes|culottes> have a tendency to ride up so.",
  "I think so, Brain, but if we covered the world in salad dressing wouldn't the asparagus feel left out?",
  "I think so, Brain, but if they called them <https://en.wikipedia.org/wiki/Happy Meal|'Sad Meals'>, kids wouldn't buy them!",
  "I think so, Brain, but me and <https://en.wikipedia.org/wiki/Pippi Longstocking|Pippi Longstocking> -- I mean, what would the children look like?",
  "I think so, Brain, but what would <https://en.wikipedia.org/wiki/Pippi Longstocking|Pippi Longstocking> look like with her hair straight?",
  "I think so, Brain, but this time _you_ put the trousers on the chimp.",
  "Well, I think so, Brain, but I can't memorize a whole opera in Yiddish.",
  "I think so, Brain, but there's still a bug stuck in here from last time.",
  "Uh, I think so, Brain, but I get all clammy inside the tent.",
  "I think so, Brain, but I don't think <https://en.wikipedia.org/wiki/Kaye Ballard|Kaye Ballard's> in the union.",
  "Yes, I am!",
  "I think so, Brain, but, <https://en.wikipedia.org/wiki/Rockettes|the Rockettes?> I mean, it's mostly girls, isn't it?",
  "I think so, Brain, but pants with horizontal stripes make me look chubby.",
  "Well, I think so _*POIT*_ but _where_ do you <https://en.wikipedia.org/wiki/Yankee Doodle|stick the feather and call it macaroni?>",
  "Well, I think so, Brain, but pantyhose are so uncomfortable in the summertime.",
  "Well, I think so, Brain, but it's a miracle that this one grew back.",
  "Well, I think so, Brain, but first you'd have to take that whole <https://en.wikipedia.org/wiki/Lake_Havasu_City,_Arizona | bridge> apart, wouldn't you?",
  "Well, I think so, Brain, but _apply North Pole_ to what?",
  "Well, I think so, Brain, but _*snort*_ no, no, it's too stupid!",
  "Umm, I think so, Don Cerebro, but, umm, why would <https://en.wikipedia.org/wiki/Sophia Loren|Sophia Loren> do a musical?",
  "Umm, I think so, Brain, but what if the chicken won't wear the nylons?",
  "I think so, Brain, but isn't that why they invented tube socks?",
  "Well, I think so Brain, but what if we stick to the seat covers?",
  "I think so Brain, but if you replace the 'P' with an 'O', my name would be Oinky, wouldn't it?",
  "Oooh, I think so Brain, but I think I'd rather eat the <https://en.wikipedia.org/wiki/Macarena (song)|Macarena.>",
  "Well, I think so _*hiccup*_, but <https://en.wikipedia.org/wiki/Robin Hood: Prince of Thieves|Kevin Costner with an English accent?>",
  "I think so, Brain, but don't you need a swimming pool to play <https://en.wikipedia.org/wiki/Marco Polo (game)|Marco Polo>?",
  "Well, I think so, Brain, but do I really need two tongues?",
  "I think so, Brain, but we're already naked.",
  "Well, I think so, Brain, but if <https://en.wikipedia.org/wiki/Blue Tail Fly|Jimmy cracks corn, and no one cares,> why does he keep doing it?",
  "I think so, Brain _*NARF*_, but don't camels spit a lot?",
  "I think so, Brain, but how will we get a pair of <https://en.wikipedia.org/wiki/Abe Vigoda|Abe Vigoda's> pants?",
  "I think so, Brain, but <https://en.wikipedia.org/wiki/Pete Rose|Pete Rose>? I mean, can we trust him?",
  "I think so, Brain, but why would <https://en.wikipedia.org/wiki/Peter Bogdanovich|Peter Bogdanovich?>",
  "I think so, Brain, but isn't a cucumber that small called a gherkin?",
  "I think so, Brain, but if we get <https://en.wikipedia.org/wiki/Sam Spade|Sam Spade>, we'll never have any puppies.",
  "I think so, Larry, and um, Brain, but how can we get seven dwarves to shave their legs?",
  "I think so, Brain, but calling it pu-pu platter? Huh, what were they thinking?",
  "I think so, Brain, but how will we get <https://en.wikipedia.org/wiki/the Spice Girls|the Spice Girls> into the paella?",
  "I think so, Brain, but if we give peas a chance, won't the lima beans feel left out?",
  "I think so, Brain, but I am running for mayor of Donkeytown and Tuesdays are booked.",
  "I think so, Brain, but if we had a snowmobile, wouldn't it melt before summer?",
  "I think so, Brain, but what kind of rides do they have in <https://en.wikipedia.org/wiki/Fabio_Lanzoni|Fabioland>?",
  "I think so, Brain, but can the Gummi Worms really live in peace with the <https://en.wikipedia.org/wiki/Peeps|Marshmallow Chicks>?",
  "Wuh, I think so, Brain, but <https://en.wikipedia.org/wiki/Does Your Chewing Gum Lose Its Flavour (On the Bedpost Overnight?)|wouldn't anything lose its flavor on the bedpost overnight>?",
  "I think so, Brain, but three round meals a day wouldn't be as hard to swallow.",
  "I think so, Brain, but if the plural of mouse is mice, wouldn't the plural of spouse be spice?",
  "Umm, I think so, Brain, but <https://en.wikipedia.org/wiki/Rub A Dub Dub|three men in a tub>? Ooh, that's unsanitary!",
  "Yes, but why does the chicken cross the road, huh, if not for love? I do not know.",
  "Wuh, I think so, Brain, but I prefer <https://en.wikipedia.org/wiki/Space Jam|Space Jelly.>",
  "Yes Brain, but if our knees bent the other way, how would we ride a bicycle?",
  "Wuh, I think so, Brain, but how will we get three pink flamingos into one pair of Capri pants?",
  "I think so, Brain, but <https://en.wikipedia.org/wiki/Tuesday Weld|Tuesday Weld> isn't a complete sentence.",
  "I think so, Brain, but why would anyone want to see <https://en.wikipedia.org/wiki/Snow White|Snow White> and the <https://en.wikipedia.org/wiki/The Seven Samurai|Seven Samurai?>",
  "I think so, Brain, but I find scratching just makes it worse.",
  "I think so, Brain, but shouldn't the bat boy be wearing a cape?",
  "I think so, Brain, but why would anyone want a depressed tongue?",
  "Um, I think so, Brainie, but why would anyone want to <https://en.wikipedia.org/wiki/Pierce Brosnan|Pierce Brosnan?>",
  "Methinks so, Brain, verily, but dost thou think <https://en.wikipedia.org/wiki/Pete Rose|Pete Rose> by any other name would still smell as sweaty?",
  "I think so, Brain, but wouldn't his movies be more suitable for children if he was named <https://en.wikipedia.org/wiki/Jean-Claude van Damme|Jean-Claude van Darn?>",
  "Wuh, I think so, Brain, but will they let the Cranberry Duchess stay in the Lincoln Bedroom?",
  "I think so, Brain, but why does a forklift have to be so big if all it does is lift forks?",
  "I think so, Brain, but if it was only supposed to be a <https://en.wikipedia.org/wiki/Gilligan's Island|three hour tour>, why did the Howells bring all their money?",
  "I think so, Brain, but <https://en.wikipedia.org/wiki/Zero Mostel|Zero Mostel> times anything will still give you Zero Mostel.",
  "I think so, Brain, but if we have nothing to fear but fear itself, why does <https://en.wikipedia.org/wiki/Eleanor Roosevelt|Eleanor Roosevelt> wear that spooky mask?",
  "I think so, Brain, but what if the hippopotamus won't wear the beach thong?",
  "Um, I think so, Brain-2, but a show about two talking lab mice? Hoo! It'll never get on the air.",
  "I think so, Brain, but Lederhosen won't stretch that far.",
  "Yeah, but I thought Madonna already had a steady bloke!",
  "I think so, Brain, but what would goats be doing in red leather turbans?",
  "I think so, Brain... but how would we ever determine Sandra Bullock's shoe size?",
  "Yes, Brain, I think so. But how do we get Twiggy to pose with an electric goose?",
  "I think so, Brain, but wouldn't mustard make it sting?",
  "I think so, Brain, but can you use the word 'asphalt' in polite society?",
  "I think so, Mr. Brain, but <https://en.wikipedia.org/wiki/Annie|if the sun'll come out tomorrow>, what's it doing right now?",
  "I think so, Brain, but aren't we out of shaving cream?",
  "Oh yes, Brain! Remind me to tape all our phone calls!",
  "Um, I think so, Brain, but I hear Hillary is the jealous type.",
  "I think so, Brain, but Madonna's stock is sinking.",
  "I think so, Brain. But does '<https://en.wikipedia.org/wiki/Chuck E. Cheeses|Chunk o' Cheesy>'s' deliver packing material?",
  "I think so, Brainwulf, but if we're Danish, where's the cream cheese? Narf!",
  "I think so, Bwain, but I don't think newspaper will fit in my underoos.",
  "Uh, I think so, Brain--but after eating newspaper all day, do I really need the extra fiber?",
  "I think so, Brain! But isn't a dreadlock hair extension awfully expensive?",
  "I think so, Brain. But will anyone other than Eskimos buy blubber-flavored chewing gum?",
  "I think so, Brain, but the ointment expired weeks ago!",
  "I think so, Brain. But would the villains really have gotten away with it, if it weren't for <https://en.wikipedia.org/wiki/Scooby-Doo|those pesky kids and their dog>?",
  "Uh, I think so Brain, but how are we gonna teach a goat to dance with flippers on?",
  "Wuhh... I think so, Brain! But let's use safflower oil this time! It's ever so much healthier!",
  "Wuh... I think so, Brain. But Cream of Gorilla Soup—well, we'd have to sell it in awfully big cans, wouldn't we?",
  "I think so, Brain. But if he left chocolate bullets instead of silver, they'd get all runny and gooey!",
  "Yes, Brain, I think so, but do nuts go with pudding?",
  "I think so, Brain, but a codpiece made from a real fish would get smelly after a while, wouldn’t it?",
  "I think so, Brain, but do those roost in this neighborhood?",
  "I think so, Brain, but is the world ready for angora bellbottoms? I mean I can see wearing them inside out, but that would--",
  "I think so, Commander Brain from Outer Space! But do we have time to grease the rockets?",
  "I think so, Doctor. But are these really the legs of a show girl?",
  "Whuh... I think so, Brain. But this time I get to play the dishwasher repairman!",
  "I think so, Brainius. But what if <https://en.wikipedia.org/wiki/The Seven Year Itch|a sudden wind were to blow up my toga>?",
  "I think so, Brain. But Trojans won’t arrive on the scene for another 300 years.",
  "I think so, Brain... but where would a yak put PVC tubing?",
  "Whuh... I think so, Brain, but... but if <https://en.wikipedia.org/wiki/Charlton Heston|Charlton Heston> doesn't eat <https://en.wikipedia.org/wiki/Soylent Green|Soylent Green>, what will he eat?",
  "I think so, Brain, but <https://en.wikipedia.org/wiki/Ben Vereen|Ben Vereen> never answered our proposition.",
  "I think so, Brain, but wouldn't an <https://en.wikipedia.org/wiki/ Itsy Bitsy Teenie Weenie Yellow Polka Dot Bikini|itsy-bitsy, teeny-weenie, yellow polka-dot one-piece> be better suited for my figure?",
  "I think so, Brain, but won't it go straight to my hips?!",
  "I think so, Ali-Brain! But isn't it cheating to use glue?",
  "Whuu... I think so, BrainPan! But if running shoes had little feet, wouldn't they need their own shoes?",
  "I think so, Brain. But what if the Earl of Essex doesn't like burlap pantaloons?",
  "I think so, Brain, but should we use dishwashing liquid or cooking oil?",
  "I think so, Brain, but would <https://en.wikipedia.org/wiki/Spanish fly|Danish flies> work just as well?",
  "We think so, Brain! But dressing like twins is so tacky.",
  "I think so, Brain, but practicing docking procedures with a goat at zero G's—it's never been done!",
  "I think so, Brain! But shouldn't we let the silk worms finish the boxer shorts before we put them on?",
  "I think so, Brain! You draw the bath and I'll fetch the alka-seltzers and candles!",
  "I think so, Brain. But the real trick will be getting Demi Moore out of the creamed corn!",
  "Wuhhh... I think so, Brain, but if <https://en.wikipedia.org/wiki/Amateur radio|a ham can operate a radio>, why can't a pig set a VCR?",
  "I think so, Brain, you'd think Lyndon Johnson would have left room for baby-kissing, wouldn't you?",
  "I think so, Brain! But won't <https://en.wikipedia.org/wiki/ J. Edgar Hoover|Mr. Hoover> notice a missing evening gown?",
  "I think so, Brain! But what's the use of having a heart-shaped tattoo if it's going to be covered by hair?",
  "I think so, Brain, but couldn't the constant use of a henna rinse lead to premature baldness?",
  "I think so, Brain. Just make sure we don't swallow each other's bubbles!",
  "I think so, Brain! But <https://en.wikipedia.org/wiki/The Wizard of Oz|ruby-studded stockings> would be mighty uncomfortable wouldn't they?",
  "I think so, Brain, but <https://en.wikipedia.org/wiki/ Titanic (1997 film)|if I have my portrait drawn, will we have time to make it to the lifeboats?>",
  "I think so, Brain! But is Chippendale's ready for '<https://en.wikipedia.org/wiki/The Full Monty|The Full Pinky>?'",
  "I think so, Brain! But do I have what it take to be the '<https://en.wikipedia.org/wiki/Michael Flatley|Lord of the Dance>'?",
  "I think so, Brain! How much deeper would the ocean be if there weren't sponges down there?",
  "Oh, I think so, Brain! But doing a clog dance in actual clogs will give me awful blisters.",
  "I think so, Brain, but nose rings are kinda passé by now.",
  "I think so, Brain, but where are we going to get a trained octopus at this time of night?",
  "I think so, Brain! But no more eels in jelly for me, thanks—I like my gelatin after lunch.",
  "I think so, Brain, but I didn’t know 90210 was a real zip code! Will <https://en.wikipedia.org/wiki/Tori Spelling|Tori> be there?",
  "I think so, Brain. But even if we found a tuxedo to fit a blowfish, who would marry it?",
  "Um, no, Cranky Mouseykin, not even in the story you made up.",
  "I think so, but where is a fish?",
  "I think so, Brain. But if Pinocchio were carved out of bacon it wouldn't be the same story, would it?",
  "Um, I think so, Brain, but wasn't Dicky Ducky released on his own recognaissance?",
  "I think so, Brain, but <https://en.wikipedia.org/wiki/Pepper Ann|Pepper Ann> makes me sneeze.",
  "I think so, Brain. But suppose we do the hokey pokey and turn ourselves around, is that what it's really all about?",
  "I think so, Brain, but just how will we get the weasel to hold still?",
  "I think so, Brain, but how are we going to get the bacon flavoring into the pencils?",
  "I think so, Brain, but <https://en.wikipedia.org/wiki/Instant Karma!|instant karma>'s always so lumpy.",
  "Umm.. I think so Bigbrainy-fishface-stovepipe-wiggleroom-Arlene, but if you get a long little doggy wouldn't you just call it a Dachshund?"
]


module.exports = (robot) ->
  robot.hear /Are you pondering what I'm pondering\?/i, (msg) ->
    pinkie = msg.random responses
    robot.customMessage {
        text: "#{pinkie}"
        channel: res.message.room
    }
